### ISSUE TITLE
Investigate inner classes

### ISSUE THREAD

**Issue by pablisco** [kopykat-kt/kopykat#34]
I have a feeling that we are not preserving "simpleNames" from ClassNames, so this could cause issues with inner classes

**Comment by pablisco** [comment]
Confirmed, this test case fails:

![20220923_013717.jpg](https://user-images.githubusercontent.com/260697/191873765-e89b691a-a293-48dd-b47e-6059cd87c8db.jpg)

**Comment by serras** [comment]
I'm going to work on it

**Comment by pablisco** [comment]
I was working on it :see\_no\_evil: But I think you found an easier solution. Reviewing it now.
