### ISSUE TITLE
Does 'superCopy' observe the 'generate' is 'annotated' setting

### ISSUE THREAD

**Issue by slawluc** [kopykat-kt/kopykat#71]
**Given these gradle settings** 
```gradle
buildscript {
    dependencies {
        .....
        classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:1.7.10-1.0.6"
    }
}

dependencies {
    .......
    ksp("at.kopyk:kopykat-ksp:1.0-rc7")
    compileOnly("at.kopyk:kopykat-annotations:1.0-rc7")
}

ksp {
    arg("generate","annotated")
    arg("mutableCopy", "true")
    arg("copyMap", "true")
    arg("hierarchyCopy", "true")
    arg("superCopy", "true")
}
``` 

**When I attempt to annotate this class with @CopyExtensions a nullable middle name**

```kotlin
@CopyExtensions
data class Person(
    val firstName: String,
    val surname: String
)
```

**Then**
It generates classes for other classes that have not been annotated with CopyExtension.

**When gradle is configured like this**
```gradle
ksp {
    arg("generate","annotated")
    arg("superCopy", "false")
}
``` 

**Then**
I only have generated classes for 'Person'

**Note**
This is the only class annotated with CopyExtension in the project

**Comment by serras** [comment]
This feature is actually being removed in favor of #68. We see now that the way you annotate things is not clear, this is part of the reason why we are removing it. Closing since this behavior won't be available in the next version.
