### ISSUE TITLE
Generated code is invalid when dealing with nullable lists

### ISSUE THREAD

**Issue by xavier-quelard** [kopykat-kt/kopykat#83]
I'm trying to use KopyKat in a context where I have data classes with nullable lists properties. For example, If I have the following data class : 

```kotlin
package person

data class Person(val d: List<String>? = null)
```

the following test will fail to build : 

```kotlin
package person

import io.kotest.core.spec.style.FunSpec

class PersonTest: FunSpec({
    test("person copy") {
        val p = Person(listOf("e"))
        val p2 = p.copy {
            d
        }
    }
})
```

I get the following error : `Type mismatch: inferred type is List<String>? but List<String> was expected`

![Capture d’écran 2023-03-10 à 16 16 07](https://user-images.githubusercontent.com/112620745/224353252-06b897c9-1b1d-475d-a4bb-b796f3c18fa1.png)

Am I doing anything wrong? 

_Versions used_ : 
_in the plugins clause of my build.gradle.kts : `id("com.google.devtools.ksp") version "1.8.10-1.0.9"`_
_in the dependencies clause of my build.gradle.kts : `ksp("at.kopyk:kopykat-ksp:1.0.1")`_

**Comment by xavier-quelard** [comment]
Thanks a lot for the fix ! Could you deploy the version 1.0.2 to Maven :) ?

**Comment by serras** [comment]
Thanks for noticing, it seems that there was a problem with publication. I've just pushed 1.0.4 to Maven Central, it should appear in a few hours.

**Comment by xavier-quelard** [comment]
Nice !
